# Generated by Django 4.0.5 on 2022-07-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableactionmodel',
            name='description_action',
            field=models.TextField(max_length=255, verbose_name='Descrição da Ação'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
