# Generated by Django 4.0.5 on 2022-07-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_alter_tableactionmodel_description_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableactionmodel',
            name='description_action',
            field=models.TextField(max_length=500, verbose_name='Descrição da Ação'),
        ),
    ]
