# Generated by Django 4.0.5 on 2022-07-20 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0005_rename_date_actions_tableactionmodel_data_acao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableactionmodel',
            name='descricao_acao',
            field=models.TextField(max_length=1000, verbose_name='Descrição da Ação'),
        ),
        migrations.AlterField(
            model_name='tableeventmodel',
            name='descricao_evento',
            field=models.TextField(default='', max_length=1000, verbose_name='Descrição do Evento'),
        ),
        migrations.CreateModel(
            name='TableIntersetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espaco_participacao', models.CharField(choices=[('(Outro)', '(Outro)'), ('CEDCA - Conselho Estadual dos Direitos da Criança e do Adolescente', 'CEDCA - Conselho Estadual dos Direitos da Criança e do Adolescente'), ('FEPETI - Forum Estatual Erradicação do Trabalho Infantil', 'FEPETI - Forum Estatual Erradicação do Trabalho Infantil'), ('CONEDE - Conselho Estadual dos Direitos da Pessoa Com Deficiência', 'CONEDE - Conselho Estadual dos Direitos da Pessoa Com Deficiência'), ('Coordenação Estadual Intersetorial do Cadúnico e PAB', 'Coordenação Estadual Intersetorial do Cadúnico e PAB'), ('GT Intersetorial do Programa Saúde na Escola', 'GT Intersetorial do Programa Saúde na Escola'), ('CIAMP - Comitê Intersetorial de População em Situação de Rua', 'CIAMP - Comitê Intersetorial de População em Situação de Rua'), ('Grupo Condutor Estadual da Rede de Cuiadados da Pessoa Com Deficiência', 'Grupo Condutor Estadual da Rede de Cuiadados da Pessoa Com Deficiência')], default='', max_length=150)),
                ('data_inicial', models.DateField(verbose_name='Data Inicial')),
                ('data_final', models.DateField(verbose_name='Data Final')),
                ('descricao', models.TextField(default='', max_length=1000, verbose_name='Descrição')),
                ('encaminhamentos', models.TextField(default='', max_length=1000, null=True, verbose_name='Encaminhamentos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
